FROM mcr.microsoft.com/mssql/server:2019-latest

ENV SA_PASSWORD Pwd12345!
ENV ACCEPT_EULA Y

USER 0

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY Deploy/db-scripts/ /usr/src/app
RUN chmod +x /usr/src/app/run-initialization.sh

CMD /bin/bash ./entrypoint.sh